### ISSUE TITLE
Melon features roadmap

### ISSUE THREAD

**Issue by victoriaquasar** [MelonRuntime/Melon#224]
> This roadmap contains features that can be added to Melon during its development. It may not include other features that will be added over time and may change.

### Web applications and features

- [x] **Built-in http applications development support**
    - [x] **REST-based development with verbs**
    - [ ] **RPC-based development with functions**
    - [ ] **GraphQL-based development with queries and mutations**
    - [x] **Static content delivery**
    - [ ] **Middlewares**

- [x] [**`fetch()`**](https://developer.mozilla.org/en-US/docs/Web/API/fetch) method
- [ ]  [**`XMLHttpRequest()`**](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/XMLHttpRequest) constructor 

### General utilities

- [ ] **`crypto` module**
    - [x] [**`randomUUID()`**](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) method
    - [ ] [**`getRandomValues()`**](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) method
